Add categories logic
artemklishch/spring-boot-task pull request #9
Opened 2024-08-06 22:37 UTC by artemklishch

BREAKING CHANGES:

*Made extra liquibase files to create categories table, insert data, create books_categories table
 *Mase respective model, mapper, controller, service and interface
 *Updated books logic from the point of the categories

Task: https://mate.academy/learn/java-spring-boot/java-spring-boot-practice-v2/linear?learnItemsFilter=All&section=practice&testTaskSlug=java_add_category_model

2024-08-07 13:39 UTC, Elena-Bruyako requested changes
see comments

2024-08-07 13:39 UTC, Elena-Bruyako commented on src/main/java/org/example/intro/controller/CategoryController.java
> +    @PreAuthorize("hasRole('USER') or hasRole('ADMIN')")
or
```suggestion
    @PreAuthorize("hasAnyRole('ADMIN', 'USER')")
```

2024-08-07 13:39 UTC, Elena-Bruyako commented on src/main/java/org/example/intro/dto/book/CreateBookDto.java
> +    @NotBlankList(message = "Book has to have at least one category")
```suggestion
    @NotEmpty(message = "Book has to have at least one category")
```

for collections

2024-08-07 13:39 UTC, Elena-Bruyako commented on src/main/java/org/example/intro/model/Book.java
> +    @ManyToMany(fetch = FetchType.LAZY)
```suggestion
    @ManyToMany
```

2024-08-07 13:39 UTC, Elena-Bruyako commented on src/main/java/org/example/intro/model/Book.java
> +    @Column(nullable = false)
```suggestion
```

2024-08-07 13:39 UTC, Elena-Bruyako commented on src/main/java/org/example/intro/model/Category.java
> +    private Boolean isDeleted = false;
```suggestion
    private boolean isDeleted = false;
```

2024-08-07 13:39 UTC, Elena-Bruyako commented on src/main/java/org/example/intro/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.findById(id).orElse(null));
don't use orElse(null));, use orElseThrow instead

2024-08-07 13:39 UTC, Elena-Bruyako commented on src/main/java/org/example/intro/service/impl/CategoryServiceImpl.java
> +                categoryRepository.findById(id).orElse(null)
same

2024-08-07 13:39 UTC, Elena-Bruyako commented on src/main/java/org/example/intro/service/impl/CategoryServiceImpl.java
> +        return categoryMapper.toDto(categoryFromDb);
```suggestion
        Category category = categoryRepository.findById(id)
                .orElseThrow(() -> new EntityNotFoundException(
                        "Category with the id " + id + " does not exist"
                ));
        categoryMapper.updateCategoryFromDto(categoryDto, category);
        return categoryMapper.toDto(repository.save(category));
```

2024-08-07 19:47 UTC, artemklishch commented on src/main/java/org/example/intro/service/impl/CategoryServiceImpl.java
> +        return categoryMapper.toDto(categoryFromDb);
++, thank you so much. updated

2024-08-07 19:47 UTC, artemklishch commented on src/main/java/org/example/intro/service/impl/CategoryServiceImpl.java
> +                categoryRepository.findById(id).orElse(null)
++, updated.

2024-08-07 19:47 UTC, artemklishch commented on src/main/java/org/example/intro/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.findById(id).orElse(null));
++, updated

2024-08-07 19:47 UTC, artemklishch commented on src/main/java/org/example/intro/model/Category.java
> +    private Boolean isDeleted = false;
++, thank you. updated.

2024-08-07 19:47 UTC, artemklishch commented on src/main/java/org/example/intro/model/Book.java
> +    @Column(nullable = false)
++, Thank you. Updated.

2024-08-07 19:47 UTC, artemklishch commented on src/main/java/org/example/intro/dto/book/CreateBookDto.java
> +    @NotBlankList(message = "Book has to have at least one category")
++, updated. thank you!

2024-08-07 19:47 UTC, artemklishch commented on src/main/java/org/example/intro/controller/CategoryController.java
> +    @PreAuthorize("hasRole('USER') or hasRole('ADMIN')")
++, thank you. updated

2024-08-09 08:02 UTC, Elena-Bruyako requested changes
see comments

2024-08-09 08:02 UTC, Elena-Bruyako commented on src/main/java/org/example/intro/controller/CategoryController.java
> +@RequestMapping(value = "/categories")
```suggestion
@RequestMapping("/categories")
```

2024-08-09 08:02 UTC, Elena-Bruyako commented on src/main/java/org/example/intro/mapper/BookMapper.java
> +    @AfterMapping
```suggestion
    @Mapping(target = "categories", ignore = true)
    Book toEntity(CreateBookDto createDto);
    
    @AfterMapping
```

2024-08-09 08:02 UTC, Elena-Bruyako commented on src/main/java/org/example/intro/mapper/BookMapper.java
> +    @AfterMapping
```suggestion
    @Mapping(target = "categoryIds", ignore = true)
    BookDto toDto(Book book);
    
    @AfterMapping
```

2024-08-09 08:02 UTC, Elena-Bruyako commented on src/main/java/org/example/intro/mapper/CategoryMapper.java
> +
```suggestion
```

2024-08-09 08:02 UTC, Elena-Bruyako commented on src/main/java/org/example/intro/model/Book.java
> +    @Column(nullable = false)
not fixed

2024-08-09 08:02 UTC, Elena-Bruyako commented on src/main/java/org/example/intro/service/impl/CategoryServiceImpl.java
> +                categoryRepository.findById(id).orElse(null)
not fixed

2024-08-09 08:12 UTC, artemklishch commented on src/main/java/org/example/intro/mapper/CategoryMapper.java
> +
++, removed space

2024-08-09 08:12 UTC, artemklishch commented on src/main/java/org/example/intro/mapper/BookMapper.java
> +    @AfterMapping
++, added space

2024-08-09 08:12 UTC, artemklishch commented on src/main/java/org/example/intro/mapper/BookMapper.java
> +    @AfterMapping
++, added space

2024-08-09 08:13 UTC, artemklishch commented on src/main/java/org/example/intro/controller/CategoryController.java
> +@RequestMapping(value = "/categories")
++, updated

2024-08-09 08:13 UTC, artemklishch commented on src/main/java/org/example/intro/service/impl/CategoryServiceImpl.java
> +                categoryRepository.findById(id).orElse(null)
++

2024-08-09 08:13 UTC, artemklishch commented on src/main/java/org/example/intro/model/Book.java
> +    @Column(nullable = false)
++

2024-08-10 13:38 UTC, sarakhmen approved these changes

2024-08-10 15:52 UTC, merged